version: "3"
services:
  system:
    container_name: system
    restart: always
    build: ./
    ports:
      - "6666:6666"
  rtsync:
    container_name: rtsync
    restart: always
    volumes:
      - ../repos/RTSYNC/:/RTSYNC/   
    working_dir: /RTSYNC/
    #build:
      #context: ./RTSYNC/
    ports:
      - "4000:4000"
