version: "3"
services:
  thesystem:
    container_name: thesystem
    restart: always
    build: ./
    ports:
      - "6666:6666"
  rtsync:
    container_name: rtsync
    restart: always
    build: ./RTSYNC/
    ports:
      - "4000:4000"
    volumes:
      - ./modules/RTSYNC:/RTSYNC

  monitor:
    container_name: monitor
    restart: always
    build: ./MONITOR
    volumes:
      - ./modules/MONITOR:/usr/share/nginx/html
      - /MONITOR/node_modules
    # volumes:
    #   - ./MONITOR:/usr/share/nginx/html

    ports:
      - "80:80"
volumes:
  RTSYNC:
  MONITOR: