version: "3"
services:
  thesystem:
    container_name: thesystem
    restart: always
    build: ./
    ports:
      - "6666:6666"
  rtsync:
    container_name: rtsync
    restart: always
    build:
      context: ./MODULES/RTSYNC/
    ports:
      - "4000:4000"

  nginx:
    container_name: http
    restart: always
    build:
      context: ./MODULES/HTTP/
    ports:
      - "80:80"
